version: 2
jobs:
  build:
    machine: true

    working_directory: ~/weather_web

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f ./docker/web/Dockerfile .
            docker build -t registry.heroku.com/$HEROKU_APP_NAME/bot ./docker/bot/
      - run:
          name: Deploy to Heroku
          command: |
             docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
             docker push registry.heroku.com/$HEROKU_APP_NAME/web
             docker push registry.heroku.com/$HEROKU_APP_NAME/bot
             
      - run:
          name: Check images
          command: docker images
          
      - run:
          name: Release web
          command: |
             docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
             heroku container:release web -a $HEROKU_APP_NAME
             
      - run:
          name: Run migrations
          command: |
             heroku run python3 manage.py migrate -a $HEROKU_APP_NAME
          
      - run:
          name: Release bot
          command: |
             heroku container:release bot -a $HEROKU_APP_NAME
             
          
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup
