version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git


workflows:
  deploy:
    jobs:
      - heroku/deploy-via-git:
          branch: circleci-project-setup
          post-steps:
            - run: python3 manage.py migrate
